name: iOS C Library Build with Tests

on:
  push:
    branches:
      - main

jobs:

  build-ios-library:
    runs-on: macos-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Install Xcode
      run: |
        sudo xcode-select --install
        sudo xcodebuild -license accept
        
    - name: Build C Library for iOS
      run: |
        # ... (省略编译静态库的步骤,与之前示例相同)
        
    - name: Run Tests
      run: |
        # 进入测试目录
        cd tests
        
        # 编译测试可执行程序
        clang -o test_runner test_main.c libmylib.a
        
        # 运行测试
        ./test_runner
        
        # 检查测试结果
        if [ $? -ne 0 ]; then
          echo "Tests failed"
          exit 1
        else
          echo "Tests passed"
        fi
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ios-library
        path: ${{ github.workspace }}/build/ios/universal