name: Auto-sync, Build, and Deploy C Library for iOS

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2 AM UTC every day
  workflow_dispatch:  # Allows manual triggering

env:
  UPSTREAM_REPO: https://github.com/dpirch/libfvad.git
  DEPLOY_BRANCH: release
  DEPLOY_FOLDER: builds
  PACKAGE_NAME: libfvad_ios

jobs:
  sync-build-and-deploy:
    runs-on: macos-latest
    
    steps:
    - name: Checkout forked repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
        
    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.co
        
    - name: Determine default branch
      id: default_branch
      run: |
        DEFAULT_BRANCH=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)
        echo "Default branch is $DEFAULT_BRANCH"
        echo "branch=$DEFAULT_BRANCH" >> $GITHUB_OUTPUT

    - name: Sync with upstream
      run: |
        git remote add upstream ${{ env.UPSTREAM_REPO }}
        git fetch upstream
        git checkout -b temp-branch
        git branch -D master || true
        git checkout -b master upstream/master
        git merge upstream/master
        git push -f origin master
      
    - name: Check for updates
      id: check_updates
      run: |
        if git diff --quiet HEAD@{1} HEAD; then
          echo "No updates from upstream. Skipping build."
          echo "updated=false" >> $GITHUB_OUTPUT
        else
          echo "Updates detected. Proceeding with build."
          echo "updated=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Install Dependencies
      if: steps.check_updates.outputs.updated == 'true'
      run: |
        brew install cmake
        brew install llvm
        
    - name: Setup environment
      if: steps.check_updates.outputs.updated == 'true'
      run: |
        echo 'export PATH="/opt/homebrew/opt/llvm/bin:$PATH"' >> $GITHUB_ENV
        echo 'export LDFLAGS="-L/opt/homebrew/opt/llvm/lib/c++ -L/opt/homebrew/opt/llvm/lib -lunwind"' >> $GITHUB_ENV
        echo 'export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"' >> $GITHUB_ENV

    - name: Download iOS toolchain
      if: steps.check_updates.outputs.updated == 'true'
      run: |
        curl -L https://raw.githubusercontent.com/leetal/ios-cmake/master/ios.toolchain.cmake -o ios.toolchain.cmake

    - name: Build C Library for iOS
      if: steps.check_updates.outputs.updated == 'true'
      run: |
        mkdir -p build && cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=../ios.toolchain.cmake -DPLATFORM=OS64 ..
        make VERBOSE=1
        
    - name: Create universal binary
      if: steps.check_updates.outputs.updated == 'true'
      run: |
        cd build
        LIB_FILE=$(find . -name "*.a" | head -n 1)
        if [ -z "$LIB_FILE" ]; then
          echo "No .a file found in build directory"
          exit 1
        fi
        lipo -create "$LIB_FILE" -output libfvad_universal.a

    - name: Prepare files for release and repository
      if: steps.check_updates.outputs.updated == 'true'
      run: |
        mkdir -p ${{ env.PACKAGE_NAME }}
        cp build/libfvad_universal.a ${{ env.PACKAGE_NAME }}/
        cp include/*.h ${{ env.PACKAGE_NAME }}/
        zip -r ${{ env.PACKAGE_NAME }}.zip ${{ env.PACKAGE_NAME }}

    - name: Create Release
      if: steps.check_updates.outputs.updated == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Ensure we're on the default branch of the forked repo
        git checkout ${{ steps.default_branch.outputs.branch }}
        # Create the release in the current (forked) repository
        gh release create v${{ github.run_number }} \
          --repo ${{ github.repository }} \
          --title "Release ${{ github.run_number }}" \
          --notes "Automated release for build ${{ github.run_number }}" \
          ${{ env.PACKAGE_NAME }}.zip
        
    - name: Checkout deploy branch
      if: steps.check_updates.outputs.updated == 'true'
      run: |
        git fetch origin
        git checkout ${{ env.DEPLOY_BRANCH }} || git checkout -b ${{ env.DEPLOY_BRANCH }}
        git pull origin ${{ env.DEPLOY_BRANCH }} || true
        
    - name: Copy files to deploy folder
      if: steps.check_updates.outputs.updated == 'true'
      run: |
        mkdir -p ${{ env.DEPLOY_FOLDER }}/${{ env.PACKAGE_NAME }}
        cp ${{ env.PACKAGE_NAME }}/* ${{ env.DEPLOY_FOLDER }}/${{ env.PACKAGE_NAME }}/
        
    - name: Commit and push to deploy branch
      if: steps.check_updates.outputs.updated == 'true'
      run: |
        git add ${{ env.DEPLOY_FOLDER }}/${{ env.PACKAGE_NAME }}
        git commit -m "Update ${{ env.PACKAGE_NAME }} from build ${{ github.run_number }}"
        git push origin ${{ env.DEPLOY_BRANCH }}