name: Build C Library for iOS

on:
    workflow_dispatch:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:

  build-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: |
        brew install cmake
        brew install llvm
        
    - name: Build C Library for iOS
      run: |
        mkdir -p build && cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/cmake/ios.toolchain.cmake -DIOS_PLATFORM=OS64 ..
        make
        lipo -create libMyLib.a -output libMyLib.a
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: libMyLib.a
        path: build/libMyLib.a